CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,

    movement_type VARCHAR(30) NOT NULL,

    quantity INTEGER NOT NULL,
    stock_before INTEGER NOT NULL,
    stock_after INTEGER NOT NULL,

    changed_by_user_id BIGINT NOT NULL,
    changed_by_username VARCHAR(100) NOT NULL,

    reason VARCHAR(500),

    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_stock_movements_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT fk_stock_movements_changed_by_user
        FOREIGN KEY (changed_by_user_id)
        REFERENCES users(id),

    CONSTRAINT chk_stock_movements_quantity
        CHECK (quantity <> 0),

    CONSTRAINT chk_stock_movements_stock_before
        CHECK (stock_before >= 0),

    CONSTRAINT chk_stock_movements_stock_after
        CHECK (stock_after >= 0),

    CONSTRAINT chk_stock_movements_stock_consistency
        CHECK (stock_after = stock_before + quantity)
);

CREATE INDEX idx_stock_movements_product_changed_at
    ON stock_movements(product_id, changed_at DESC);