CREATE TABLE
    tax_categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(30) NOT NULL,
        name VARCHAR(100) NOT NULL,
        tax_rate NUMERIC(5, 2) NOT NULL,
        active BOOLEAN NOT NULL DEFAULT TRUE,
        display_order INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_tax_categories_code UNIQUE (code),
        CONSTRAINT chk_tax_categories_tax_rate CHECK (
            tax_rate >= 0
            AND tax_rate <= 100
        )
    );

INSERT INTO
    tax_categories (code, name, tax_rate, active, display_order)
VALUES
    ('STANDARD', '標準税率', 10.00, TRUE, 10),
    ('REDUCED', '軽減税率', 8.00, TRUE, 20);

ALTER TABLE products
ADD COLUMN tax_category_id BIGINT;

UPDATE products
SET
    tax_category_id = (
        SELECT
            id
        FROM
            tax_categories
        WHERE
            code = 'STANDARD'
    );

ALTER TABLE products
ALTER COLUMN tax_category_id
SET
    NOT NULL;

ALTER TABLE products ADD CONSTRAINT fk_products_tax_category FOREIGN KEY (tax_category_id) REFERENCES tax_categories (id);

CREATE INDEX idx_products_tax_category_id ON products (tax_category_id);