CREATE TABLE
    order_charges (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL,
        charge_type VARCHAR(30) NOT NULL,
        name VARCHAR(100) NOT NULL,
        amount INTEGER NOT NULL,
        tax_category_id BIGINT NOT NULL,
        tax_category_code VARCHAR(30) NOT NULL,
        tax_category_name VARCHAR(100) NOT NULL,
        tax_rate NUMERIC(5, 2) NOT NULL,
        display_order INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_order_charges_order FOREIGN KEY (order_id) REFERENCES orders (id),
        CONSTRAINT fk_order_charges_tax_category FOREIGN KEY (tax_category_id) REFERENCES tax_categories (id),
        CONSTRAINT chk_order_charges_amount CHECK (amount >= 0)
    );

CREATE INDEX idx_order_charges_order_id ON order_charges (order_id);

CREATE INDEX idx_order_charges_tax_category_id ON order_charges (tax_category_id);