ALTER TABLE orders
ADD COLUMN content_revision INTEGER NOT NULL DEFAULT 0;

ALTER TABLE orders ADD CONSTRAINT chk_orders_content_revision CHECK (content_revision >= 0);

CREATE TABLE
    order_content_change_histories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL,
        change_source VARCHAR(20) NOT NULL,
        reason VARCHAR(500),
        changed_by_type VARCHAR(20) NOT NULL,
        changed_by_account_id BIGINT,
        changed_by_username VARCHAR(100) NOT NULL,
        old_item_subtotal INTEGER NOT NULL,
        new_item_subtotal INTEGER NOT NULL,
        old_charge_total INTEGER NOT NULL,
        new_charge_total INTEGER NOT NULL,
        old_tax_amount INTEGER NOT NULL,
        new_tax_amount INTEGER NOT NULL,
        old_total_amount INTEGER NOT NULL,
        new_total_amount INTEGER NOT NULL,
        changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_order_content_change_histories_order FOREIGN KEY (order_id) REFERENCES orders (id),
        CONSTRAINT chk_order_content_change_histories_old_item_subtotal CHECK (old_item_subtotal >= 0),
        CONSTRAINT chk_order_content_change_histories_new_item_subtotal CHECK (new_item_subtotal >= 0),
        CONSTRAINT chk_order_content_change_histories_old_charge_total CHECK (old_charge_total >= 0),
        CONSTRAINT chk_order_content_change_histories_new_charge_total CHECK (new_charge_total >= 0),
        CONSTRAINT chk_order_content_change_histories_old_tax_amount CHECK (old_tax_amount >= 0),
        CONSTRAINT chk_order_content_change_histories_new_tax_amount CHECK (new_tax_amount >= 0),
        CONSTRAINT chk_order_content_change_histories_old_total_amount CHECK (old_total_amount >= 0),
        CONSTRAINT chk_order_content_change_histories_new_total_amount CHECK (new_total_amount >= 0)
    );

CREATE INDEX idx_order_content_change_histories_order_changed_at ON order_content_change_histories (order_id, changed_at, id);

CREATE TABLE
    order_content_change_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        history_id BIGINT NOT NULL,
        order_item_id BIGINT,
        product_id BIGINT NOT NULL,
        product_name VARCHAR(100) NOT NULL,
        change_type VARCHAR(20) NOT NULL,
        old_price INTEGER,
        new_price INTEGER,
        old_quantity INTEGER,
        new_quantity INTEGER,
        old_subtotal INTEGER,
        new_subtotal INTEGER,
        old_tax_category_id BIGINT,
        new_tax_category_id BIGINT,
        old_tax_category_code VARCHAR(30),
        new_tax_category_code VARCHAR(30),
        old_tax_category_name VARCHAR(100),
        new_tax_category_name VARCHAR(100),
        old_tax_rate NUMERIC(5, 2),
        new_tax_rate NUMERIC(5, 2),
        CONSTRAINT fk_order_content_change_items_history FOREIGN KEY (history_id) REFERENCES order_content_change_histories (id)
    );

CREATE INDEX idx_order_content_change_items_history_id ON order_content_change_items (history_id);

CREATE TABLE
    order_content_change_charges (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        history_id BIGINT NOT NULL,
        order_charge_id BIGINT,
        charge_type VARCHAR(30) NOT NULL,
        change_type VARCHAR(20) NOT NULL,
        old_name VARCHAR(100),
        new_name VARCHAR(100),
        old_amount INTEGER,
        new_amount INTEGER,
        old_tax_category_id BIGINT,
        new_tax_category_id BIGINT,
        old_tax_category_code VARCHAR(30),
        new_tax_category_code VARCHAR(30),
        old_tax_category_name VARCHAR(100),
        new_tax_category_name VARCHAR(100),
        old_tax_rate NUMERIC(5, 2),
        new_tax_rate NUMERIC(5, 2),
        old_display_order INTEGER,
        new_display_order INTEGER,
        CONSTRAINT fk_order_content_change_charges_history FOREIGN KEY (history_id) REFERENCES order_content_change_histories (id)
    );

CREATE INDEX idx_order_content_change_charges_history_id ON order_content_change_charges (history_id);