CREATE TABLE
    payments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL,
        provider VARCHAR(30) NOT NULL,
        payment_method VARCHAR(30) NOT NULL,
        status VARCHAR(30) NOT NULL,
        amount INTEGER NOT NULL,
        provider_payment_id VARCHAR(255),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
        CONSTRAINT chk_payments_amount CHECK (amount > 0)
    );

CREATE INDEX idx_payments_order_id ON payments (order_id);

CREATE UNIQUE INDEX uq_payments_provider_payment_id ON payments (provider, provider_payment_id)
WHERE
    provider_payment_id IS NOT NULL;

CREATE TABLE
    payment_transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        payment_id BIGINT NOT NULL,
        transaction_type VARCHAR(30) NOT NULL,
        status VARCHAR(30) NOT NULL,
        amount INTEGER NOT NULL,
        order_content_revision INTEGER NOT NULL,
        idempotency_key VARCHAR(100) NOT NULL,
        provider_transaction_id VARCHAR(255),
        failure_code VARCHAR(100),
        failure_message VARCHAR(500),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        completed_at TIMESTAMP,
        CONSTRAINT fk_payment_transactions_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
        CONSTRAINT chk_payment_transactions_amount CHECK (amount > 0),
        CONSTRAINT chk_payment_transactions_order_content_revision CHECK (order_content_revision >= 0),
        CONSTRAINT uq_payment_transactions_idempotency_key UNIQUE (idempotency_key)
    );

CREATE INDEX idx_payment_transactions_payment_id ON payment_transactions (payment_id);