CREATE TABLE payment_discrepancy_audit_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    candidate_count INTEGER,
    success_count INTEGER NOT NULL DEFAULT 0,
    inconsistent_count INTEGER NOT NULL DEFAULT 0,
    in_progress_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    duration_ms BIGINT,
    error_code VARCHAR(50),
    error_summary VARCHAR(1000),
    instance_id VARCHAR(100) NOT NULL,
    CONSTRAINT chk_payment_audit_runs_execution_type CHECK (execution_type = 'SCHEDULED'),
    CONSTRAINT chk_payment_audit_runs_status CHECK (status IN ('RUNNING', 'SUCCESS', 'PARTIAL_FAILURE', 'FAILED')),
    CONSTRAINT chk_payment_audit_runs_nonnegative CHECK (
        (candidate_count IS NULL OR candidate_count >= 0)
        AND success_count >= 0 AND inconsistent_count >= 0 AND in_progress_count >= 0
        AND skipped_count >= 0 AND failure_count >= 0
        AND (duration_ms IS NULL OR duration_ms >= 0)
    ),
    CONSTRAINT chk_payment_audit_runs_success_subcounts CHECK (
        inconsistent_count::BIGINT + in_progress_count <= success_count
    ),
    CONSTRAINT chk_payment_audit_runs_candidate_counts CHECK (
        (candidate_count IS NULL AND success_count = 0 AND inconsistent_count = 0
            AND in_progress_count = 0 AND skipped_count = 0 AND failure_count = 0)
        OR (candidate_count IS NOT NULL AND success_count::BIGINT + skipped_count + failure_count <= candidate_count)
    ),
    CONSTRAINT chk_payment_audit_runs_completion_times CHECK (
        (status = 'RUNNING' AND finished_at IS NULL AND duration_ms IS NULL)
        OR (status <> 'RUNNING' AND finished_at IS NOT NULL AND duration_ms IS NOT NULL)
    ),
    CONSTRAINT chk_payment_audit_runs_success CHECK (
        status <> 'SUCCESS' OR (candidate_count IS NOT NULL AND failure_count = 0
            AND success_count::BIGINT + skipped_count = candidate_count)
    ),
    CONSTRAINT chk_payment_audit_runs_partial_failure CHECK (
        status <> 'PARTIAL_FAILURE' OR (candidate_count IS NOT NULL AND failure_count >= 1
            AND success_count::BIGINT + skipped_count >= 1
            AND success_count::BIGINT + skipped_count + failure_count = candidate_count)
    )
);

CREATE INDEX idx_payment_audit_runs_started ON payment_discrepancy_audit_runs (execution_type, started_at DESC, id DESC);
CREATE INDEX idx_payment_audit_runs_finished ON payment_discrepancy_audit_runs (execution_type, status, finished_at DESC, id DESC);
CREATE INDEX idx_payment_audit_runs_running ON payment_discrepancy_audit_runs (started_at) WHERE status = 'RUNNING';
