-- Notification persistence only. No scheduler or mail delivery is enabled by this migration.
CREATE TABLE payment_audit_notification_states (
    warning_type VARCHAR(32) PRIMARY KEY,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    episode_no BIGINT NOT NULL DEFAULT 0,
    first_observed_at TIMESTAMPTZ,
    last_evaluated_at TIMESTAMPTZ,
    last_observed_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_payment_audit_notification_states_type CHECK (warning_type IN
        ('CONSECUTIVE_FAILURES', 'LATEST_FAILURE', 'LONG_RUNNING', 'DELAYED', 'NO_HISTORY', 'LONG_UNHANDLED')),
    CONSTRAINT chk_payment_audit_notification_states_counts CHECK (episode_no >= 0 AND version >= 0),
    CONSTRAINT chk_payment_audit_notification_states_episode CHECK (
        (episode_no = 0 AND NOT active AND first_observed_at IS NULL AND resolved_at IS NULL)
        OR (episode_no > 0 AND first_observed_at IS NOT NULL AND last_observed_at IS NOT NULL
            AND ((active AND resolved_at IS NULL) OR (NOT active AND resolved_at IS NOT NULL)))
    ),
    CONSTRAINT chk_payment_audit_notification_states_times CHECK (
        (last_observed_at IS NULL OR last_observed_at >= first_observed_at)
        AND (resolved_at IS NULL OR resolved_at >= first_observed_at)
    )
);

INSERT INTO payment_audit_notification_states (warning_type) VALUES
    ('CONSECUTIVE_FAILURES'), ('LATEST_FAILURE'), ('LONG_RUNNING'),
    ('DELAYED'), ('NO_HISTORY'), ('LONG_UNHANDLED');

CREATE TABLE payment_audit_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(24) NOT NULL,
    evaluated_at TIMESTAMPTZ NOT NULL,
    from_address VARCHAR(254) NOT NULL,
    -- Creation-time snapshot. Delivery must intersect it with current configured recipients.
    recipients TEXT[] NOT NULL,
    recipient_set_hash CHAR(64) NOT NULL,
    admin_url TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL,
    retry_delay_ms BIGINT NOT NULL,
    next_attempt_at TIMESTAMPTZ,
    claim_token UUID,
    claimed_by UUID,
    lease_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    close_reason VARCHAR(40),
    delivery_uncertain BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_payment_audit_notifications_status CHECK (status IN
        ('PENDING', 'CLAIMED', 'SENDING', 'RETRY_WAIT', 'SENT', 'EXHAUSTED', 'CANCELLED')),
    CONSTRAINT chk_payment_audit_notifications_recipients CHECK (
        array_ndims(recipients) = 1 AND cardinality(recipients) BETWEEN 1 AND 20
        AND array_position(recipients, NULL) IS NULL AND array_position(recipients, '') IS NULL
    ),
    CONSTRAINT chk_payment_audit_notifications_hash CHECK (recipient_set_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_payment_audit_notifications_attempts CHECK (
        max_attempts BETWEEN 1 AND 10 AND attempt_count BETWEEN 0 AND max_attempts AND retry_delay_ms > 0
    ),
    CONSTRAINT chk_payment_audit_notifications_claim CHECK (
        (status IN ('CLAIMED', 'SENDING') AND claim_token IS NOT NULL AND claimed_by IS NOT NULL AND lease_until IS NOT NULL)
        OR (status NOT IN ('CLAIMED', 'SENDING') AND claim_token IS NULL AND claimed_by IS NULL AND lease_until IS NULL)
    ),
    CONSTRAINT chk_payment_audit_notifications_next_attempt CHECK (
        (status IN ('PENDING', 'RETRY_WAIT') AND next_attempt_at IS NOT NULL)
        OR (status NOT IN ('PENDING', 'RETRY_WAIT') AND next_attempt_at IS NULL)
    ),
    CONSTRAINT chk_payment_audit_notifications_completion CHECK (
        (status IN ('SENT', 'EXHAUSTED', 'CANCELLED') AND closed_at IS NOT NULL)
        OR (status NOT IN ('SENT', 'EXHAUSTED', 'CANCELLED') AND closed_at IS NULL)
    ),
    CONSTRAINT chk_payment_audit_notifications_sent CHECK (
        (status = 'SENT' AND sent_at IS NOT NULL AND close_reason IS NULL)
        OR (status <> 'SENT' AND sent_at IS NULL)
    ),
    CONSTRAINT chk_payment_audit_notifications_close_reason CHECK (
        (status = 'EXHAUSTED' AND close_reason IS NOT NULL AND close_reason = 'MAX_ATTEMPTS')
        OR (status = 'CANCELLED' AND close_reason IS NOT NULL AND close_reason IN ('RESOLVED', 'NO_VALID_RECIPIENTS'))
        OR (status NOT IN ('EXHAUSTED', 'CANCELLED') AND close_reason IS NULL)
    ),
    CONSTRAINT chk_payment_audit_notifications_progress CHECK (
        (status <> 'PENDING' OR attempt_count = 0)
        AND (status NOT IN ('SENDING', 'SENT', 'RETRY_WAIT', 'EXHAUSTED') OR attempt_count >= 1)
        AND (status <> 'EXHAUSTED' OR attempt_count = max_attempts)
        AND (status <> 'RETRY_WAIT' OR attempt_count < max_attempts)
    ),
    CONSTRAINT chk_payment_audit_notifications_times CHECK (
        updated_at >= created_at AND (sent_at IS NULL OR sent_at >= created_at)
        AND (closed_at IS NULL OR closed_at >= created_at)
    )
);

CREATE INDEX idx_payment_audit_notifications_pending ON payment_audit_notifications (next_attempt_at, id)
    WHERE status IN ('PENDING', 'RETRY_WAIT');
CREATE INDEX idx_payment_audit_notifications_lease ON payment_audit_notifications (lease_until, id)
    WHERE status IN ('CLAIMED', 'SENDING');
CREATE INDEX idx_payment_audit_notifications_created ON payment_audit_notifications (created_at DESC, id DESC);

CREATE TABLE payment_audit_notification_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    warning_type VARCHAR(32) NOT NULL,
    episode_no BIGINT NOT NULL,
    item_status VARCHAR(24) NOT NULL,
    first_observed_at TIMESTAMPTZ NOT NULL,
    related_at TIMESTAMPTZ,
    warning_count BIGINT,
    error_code VARCHAR(50),
    resolved_at TIMESTAMPTZ,
    removed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_payment_audit_notification_items_notification FOREIGN KEY (notification_id)
        REFERENCES payment_audit_notifications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_audit_notification_items_state FOREIGN KEY (warning_type)
        REFERENCES payment_audit_notification_states (warning_type) ON DELETE RESTRICT,
    CONSTRAINT uq_payment_audit_notification_items_episode UNIQUE (warning_type, episode_no),
    CONSTRAINT chk_payment_audit_notification_items_counts CHECK (
        episode_no >= 1 AND (warning_count IS NULL OR warning_count >= 0)
    ),
    CONSTRAINT chk_payment_audit_notification_items_status CHECK (item_status IN ('INCLUDED', 'REMOVED_RESOLVED')),
    CONSTRAINT chk_payment_audit_notification_items_removed CHECK (
        (item_status = 'REMOVED_RESOLVED' AND resolved_at IS NOT NULL AND removed_at IS NOT NULL)
        OR (item_status = 'INCLUDED' AND removed_at IS NULL)
    ),
    CONSTRAINT chk_payment_audit_notification_items_error CHECK (error_code IS NULL OR error_code IN
        ('ALL_ITEMS_FAILED', 'CANDIDATE_FETCH_FAILED', 'EXECUTION_ABORTED', 'ITEM_FAILURE')),
    CONSTRAINT chk_payment_audit_notification_items_times CHECK (
        (resolved_at IS NULL OR resolved_at >= first_observed_at)
        AND (removed_at IS NULL OR removed_at >= resolved_at)
    )
);
CREATE INDEX idx_payment_audit_notification_items_notification ON payment_audit_notification_items (notification_id, id);

CREATE TABLE payment_audit_notification_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    claim_token UUID NOT NULL,
    result VARCHAR(24) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    failure_code VARCHAR(40),
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    -- Actual effective recipients for this attempt, after excluding removed addresses.
    recipients TEXT[] NOT NULL,
    CONSTRAINT fk_payment_audit_notification_attempts_notification FOREIGN KEY (notification_id)
        REFERENCES payment_audit_notifications (id) ON DELETE RESTRICT,
    CONSTRAINT uq_payment_audit_notification_attempts_number UNIQUE (notification_id, attempt_no),
    CONSTRAINT uq_payment_audit_notification_attempts_token UNIQUE (claim_token),
    CONSTRAINT chk_payment_audit_notification_attempts_number CHECK (attempt_no BETWEEN 1 AND 10),
    CONSTRAINT chk_payment_audit_notification_attempts_result CHECK (result IN ('IN_PROGRESS', 'SUCCESS', 'FAILURE', 'UNKNOWN')),
    CONSTRAINT chk_payment_audit_notification_attempts_finished CHECK (
        (result = 'IN_PROGRESS' AND finished_at IS NULL AND failure_code IS NULL)
        OR (result = 'SUCCESS' AND finished_at IS NOT NULL AND failure_code IS NULL)
        OR (result IN ('FAILURE', 'UNKNOWN') AND finished_at IS NOT NULL AND failure_code IS NOT NULL)
    ),
    CONSTRAINT chk_payment_audit_notification_attempts_failure CHECK (failure_code IS NULL OR failure_code IN
        ('SMTP_CONNECT_FAILED', 'SMTP_REJECTED', 'SMTP_SEND_FAILED', 'SEND_DEADLINE_EXCEEDED', 'CLAIM_LOST')),
    CONSTRAINT chk_payment_audit_notification_attempts_times CHECK (finished_at IS NULL OR finished_at >= started_at),
    CONSTRAINT chk_payment_audit_notification_attempts_recipients CHECK (
        array_ndims(recipients) = 1 AND cardinality(recipients) BETWEEN 1 AND 20
        AND array_position(recipients, NULL) IS NULL AND array_position(recipients, '') IS NULL
    )
);
