CREATE TABLE categories (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    name VARCHAR(100)
        NOT NULL,

    active BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_categories_name
        UNIQUE (name)
);

INSERT INTO categories (
    name,
    active
)
VALUES (
    '未分類',
    TRUE
);

ALTER TABLE products
    ADD COLUMN category_id BIGINT;

UPDATE products
SET category_id = (
    SELECT id
    FROM categories
    WHERE name = '未分類'
);

ALTER TABLE products
    ALTER COLUMN category_id
    SET NOT NULL;

ALTER TABLE products
    ADD CONSTRAINT fk_products_category
    FOREIGN KEY (category_id)
    REFERENCES categories(id);